### PR TITLE
Improved helm-spacemacs//faq-candidates

### PR DESCRIPTION
**Pull request by TheBB**
I couldn't figure out what the difference was between your function and the one you copied from. Seems to me you can just call that one instead.

I called `substring-no-properies` on each entry to get rid of the colours, and matched a regexp (basically `topic/title`) on each of them. That filters away the entries which aren't questions, and it also lets us display them in a nicer manner by picking out the capture groups (with `match-string`).

### CODE REVIEW

**Comment by StreakyCobra** [comment]
There isn't any difference. I did this because I thought it was better to copy a single function than loading a module. But I also prefer this way, it's much cleaner :-)

I like your modification, two questions:
- With this you assume there will be only levels 2 and 3 in the FAQ, or if there is more it will be displayed as Level2: Level3/Level4?
- Do I merge you PR, then PR the branch to spacemacs? Or do I group everything in one commit and include you in the message body?

**Comment by TheBB** [comment]
> With this you assume there will be only levels 2 and 3 in the FAQ, or if there is more it will be displayed as Level2: Level3/Level4?

Yeah. I guess we can deal with that if and when it happens.

> Do I merge you PR, then PR the branch to spacemacs? Or do I group everything in one commit and include you in the message body?

Typically the first, but if you want to squash the commits, I don't mind.

**Comment by StreakyCobra** [comment]
> Typically the first

I agree, but I was unsure because of the [guidelines](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.org#ideally-and-for-simple-prs)

**Comment by TheBB** [comment]
Ah right. Well, you can squash then. I don't really care.

**Pull request merged**
